#!/bin/bash
#SBATCH -D /ufrc/lam/johnson2319/NGEE/Automation
#SBATCH --job-name=matrix_mult1024np5.job
#SBATCH --mail-type=ALL
#SBATCH --mail-user=johnson@hcs.ufl.edu
#SBATCH --ntasks=5
#SBATCH --account=ccmt
#SBATCH --qos=ccmt
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:5:00
#SBATCH -o test/matrix_mult1024np5.out
#SBATCH -e test/matrix_mult1024np5.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 5 ./mat_mult.o 1024
