#!/bin/bash
#SBATCH -D /ufrc/bala/aravindneela/NGEE/CMT-bone-BE/mpi/rtime
#SBATCH --job-name=job-bonebe-es10ex7ey5ez5.job
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=aravindneela@ufl.edu
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:45:00
#SBATCH -o data/bonebe-es10ex7ey5ez5.out
#SBATCH -e data/bonebe-es10ex7ey5ez5.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 8 ./cmtbonebe 100 10 7 5 5
