#!/bin/bash
#SBATCH -D /home/johnson/Documents/NGEE/Automation/output_examples
#SBATCH --job-name=matrix_mult64np3.job
#SBATCH --mail-type=ALL
#SBATCH --mail-user=johnson@hcs.ufl.edu
#SBATCH --ntasks=3
#SBATCH --account=ccmt
#SBATCH --qos=ccmt
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:15:00
#SBATCH -o temp/matrix_mult64np3.out
#SBATCH -e temp/matrix_mult64np3.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 3 ./mat_mult.o 64
