#!/bin/bash
#SBATCH -D /ufrc/bala/aravindneela/NGEE/CMT-bone-BE/mpi/rtime
#SBATCH --job-name=job-bonebe-es10ex7ey5ez9np16.job
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=aravindneela@ufl.edu
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:45:00
#SBATCH -o data-np16/bonebe-es10ex7ey5ez9np16.out
#SBATCH -e data-np16/bonebe-es10ex7ey5ez9np16.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 16 ./cmtbonebe 100 10 7 5 9 4 2 2
