#!/bin/bash
#SBATCH -D /ufrc/bala/aravindneela/NGEE/CMT-bone-BE/mpi/rtime
#SBATCH --job-name=job-bonebe-es10ex1ey7ez2.job
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=aravindneela@ufl.edu
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:45:00
#SBATCH -o data1/bonebe-es10ex1ey7ez2.out
#SBATCH -e data1/bonebe-es10ex1ey7ez2.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 8 ./cmtbonebe 100 10 1 7 2
