#!/bin/bash
#SBATCH -D /ufrc/lam/johnson2319/NGEE/Automation/working_dir
#SBATCH --job-name=job-bonebe-es15ex2ey2ez2np8.job
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=johnson@hcs.ufl.edu
#SBATCH --ntasks=8
#SBATCH --account=ccmt
#SBATCH --qos=ccmt
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-socket=16
#SBATCH --exclusive
#SBATCH --distribution=cyclic:block
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:15:00
#SBATCH -o 3_14_test//bonebe-es15ex2ey2ez2np8.out
#SBATCH -e 3_14_test//bonebe-es15ex2ey2ez2np8.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 8 ./cmtbonebe 100 15 2 2 2 2 2 2
