#!/bin/bash
#SBATCH -D /ufrc/lam/johnson2319/NGEE/Automation/working_dir
#SBATCH --job-name=matrix_mult1024np2.job
#SBATCH --mail-type=ALL
#SBATCH --mail-user=johnson@hcs.ufl.edu
#SBATCH --ntasks=2
#SBATCH --account=ccmt
#SBATCH --qos=ccmt
#SBATCH --mem-per-cpu=1gb
#SBATCH -t 00:5:00
#SBATCH -o 3_14_test/matrix_mult1024np2.out
#SBATCH -e 3_14_test/matrix_mult1024np2.err
 
module load intel/2016.0.109 openmpi/1.10.2
 
mpirun -np 2 ./mat_mult.o 1024
